# Environment to match SQL Server's ML Services
# Buck Woody, 11/07/2018

name: HybridML

dependencies:
  - python=3.6
  - pandas==0.19.2

  - pip:
    - numpy==1.12.1
    - ipykernel
    - matplotlib
    - seaborn
    - sklearn
